name: Project Build

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Run action
      uses: lpmi-13/learning-space-single-setup@v1.0.0
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPOSITORY: ${{ github.repository }}
      with:
        # reference local configuration file
        path: ./.projects/board.yml
