# This automation reindexes the Vision cloud instance with scheduling data from Docebo
name: "Docebo Schedule Reindex"

on:
#   schedule:
#     # Run hourly at :55
#     - cron:  '55 * * * *'

  workflow_dispatch:


jobs:
  run-reindex-request:
    runs-on: ubuntu-latest
    steps:
    - name: Reindex request
      env:
        ENDPOINT: ${{ secrets.VISION_ENDPOINT }}
      run: |
        curl -XPOST -u "${{secrets.VISION_TRG_INT_USER}}":"${{ secrets.VISION_TRG_INT_PASS }}" 
        "$ENDPOINT"/_reindex" -H 'Content-Type: application/json' -d 
        '{"source":{"index":"docebo_training_schedule"},"dest":{"index":"trg_docebo_training_schedule"}}'
    
    - name: Update enrich index
      env:
        ENDPOINT: ${{ secrets.VISION_ENDPOINT }}
      run: |
        curl -XPOST -u "${{ secrets.VISION_TRG_INT_USER }}":"${{ secrets.VISION_TRG_INT_PASS }}" 
        "$ENDPOINT"/_enrich/policy/delivery_info_policy/_execute"
